//! Core Types and Data Structures
//!
//! Defines the fundamental types used throughout the MCP Context Browser.
//! These types represent the core domain model for semantic code search.

use serde::{Deserialize, Serialize};
use validator::{Validate, ValidationError};

/// Vector embedding representation
///
/// Represents a numerical vector embedding generated by an AI model.
/// Embeddings are used for semantic similarity search and comparison.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default, Validate)]
pub struct Embedding {
    /// The embedding vector values
    #[validate(length(min = 1, message = "Embedding vector cannot be empty"))]
    pub vector: Vec<f32>,
    /// Name of the model that generated this embedding
    #[validate(length(min = 1, message = "Model name cannot be empty"))]
    pub model: String,
    /// Dimensionality of the embedding vector
    #[validate(range(min = 1, message = "Dimensions must be positive"))]
    pub dimensions: usize,
}

/// Processed code chunk with metadata
///
/// Represents a chunk of code that has been processed for indexing.
/// Contains the actual code content along with metadata for search and retrieval.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Validate)]
pub struct CodeChunk {
    /// Unique identifier for this code chunk
    #[validate(length(min = 1, message = "ID cannot be empty"))]
    pub id: String,
    /// The actual code content
    #[validate(length(min = 1, max = 10000, message = "Content must be between 1 and 10000 characters"))]
    pub content: String,
    /// Path to the source file
    #[validate(length(min = 1, message = "File path cannot be empty"))]
    pub file_path: String,
    /// Starting line number in the source file
    #[validate(range(min = 1, message = "Start line must be positive"))]
    pub start_line: u32,
    /// Ending line number in the source file
    #[validate(range(min = 1, message = "End line must be positive"))]
    pub end_line: u32,
    /// Programming language of the code
    pub language: Language,
    /// Additional metadata as JSON (context, AST info, etc.)
    pub metadata: serde_json::Value,
}

/// Supported programming languages
///
/// Defines the programming languages that the system can process.
/// Language detection is based on file extensions and syntax analysis.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum Language {
    Rust,
    Python,
    JavaScript,
    TypeScript,
    Go,
    Java,
    C,
    Cpp,
    CSharp,
    Php,
    Ruby,
    Swift,
    Kotlin,
    Scala,
    Haskell,
    Unknown,
}

impl Language {
    pub fn from_extension(ext: &str) -> Self {
        match ext.to_lowercase().as_str() {
            "rs" => Language::Rust,
            "py" => Language::Python,
            "js" => Language::JavaScript,
            "ts" => Language::TypeScript,
            "go" => Language::Go,
            "java" => Language::Java,
            "c" => Language::C,
            "cpp" | "cc" | "cxx" => Language::Cpp,
            "cs" => Language::CSharp,
            "php" => Language::Php,
            "rb" => Language::Ruby,
            "swift" => Language::Swift,
            "kt" => Language::Kotlin,
            "scala" => Language::Scala,
            "hs" => Language::Haskell,
            _ => Language::Unknown,
        }
    }
}

/// Semantic search result
///
/// Represents a single result from a semantic code search operation.
/// Contains the matched code snippet with relevance scoring and metadata.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SearchResult {
    /// Path to the file containing the match
    pub file_path: String,
    /// Line number where the match starts
    pub line_number: u32,
    /// The actual code content that matched
    pub content: String,
    /// Relevance score (higher = more relevant)
    pub score: f32,
    /// Additional metadata about the match
    pub metadata: serde_json::Value,
}

/// Indexing statistics
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct IndexingStats {
    pub total_files: u32,
    pub indexed_files: u32,
    pub total_chunks: u32,
    pub duration_ms: u64,
}

/// Configuration for embedding providers
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingConfig {
    pub provider: String,
    pub model: String,
    pub api_key: Option<String>,
    pub base_url: Option<String>,
    pub dimensions: Option<usize>,
    pub max_tokens: Option<usize>,
}

/// Configuration for vector store providers
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VectorStoreConfig {
    pub provider: String,
    pub address: Option<String>,
    pub token: Option<String>,
    pub collection: Option<String>,
    pub dimensions: Option<usize>,
}

